id: a4c-plugin-sample
name: Alien 4 Cloud Plugin sample.
version: ${project.version}
description: Sample for alien 4 cloud plugin.
configuration_class: alien4cloud.sampleplugin.ContextConfiguration
ui_entry_point: scripts/plugin.js
component_descriptors:
  - bean_name: myPluginService
    name: Say hello service.
    description: Service to say hello.
